### ISSUE TITLE
Appveyor example

### ISSUE THREAD

**Issue by gappleto97** [codeclimate/python-test-reporter#26]
Hi,

It would be nice if we could see an example using Appveyor. The syntax on Windows is sufficiently different that it isn't obvious how to make it work.

**Comment by dblandin** [comment]
Hey @gappleto97,

I'm not familiar with AppVeyor. It looks like it's focused on building, testing, and deploying .NET applications.

Do you think a Windows-specific section in the README would suffice? I'd gladly review a PR adding documentation that demonstrates syntax on Windows as it relates to this project.

**Comment by dblandin** [comment]
Going to go ahead and close this issue for now. If you have an example in mind, I'd be happy to check it out.

Thanks!
