### ISSUE TITLE
Test Reporter returning Exit Code 1

### ISSUE THREAD

**Issue by SiyavulaMachine** [codeclimate/python-test-reporter#31]
Hi Code Climate,

I seem to have frequent issues with some of my Python repos that build on Circle CI - it would appear that the code climate test reporter is having trouble communicating with your servers. It's not permanent and sometimes just resolves itself later in the day but it does happen often enough to send a few alarms that repo tests are breaking when, in fact, they aren't. The stack trace is below.

Thanks Code Climate - you guys and gals are awesome!

Richard

![code climate test reporter](https://cloud.githubusercontent.com/assets/10650767/19666350/492bfab4-9a4a-11e6-81fd-4feadb914bdb.png)

**Comment by dblandin** [comment]
Hey @SiyavulaMachine,

Thank you for the report! I just ran an SSL test on our servers and it looks like everything is fine there:

![2016-10-25-125133_1089x641_scrot](https://cloud.githubusercontent.com/assets/123595/19695658/096d77d2-9ab2-11e6-9ef2-0c3d05cefcc7.png)

source: https://www.ssllabs.com/ssltest/analyze.html?d=codeclimate.com&hideResults=on

I also searched for the error message emitted from the reporter and it looks like we might be able to install the `requests[security]` package extras to address this issue.

http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

Would you mind adding the `pip install` line to your CI config and see if the error goes away? If it does, we may want to add it as a dependency of the reporter so it's automatically pulled in when you `pip install` the test reporter.

```yaml
test:
  post:
    - pip install requests[security]
    - codeclimate-test-reporter
```

**Comment by SiyavulaMachine** [comment]
Hi Code Climate,

Sadly, that does not work. Attached is the latest traceback. Appears that the install happens just fine but a whole new error occurs. This is the test section of my circle.yml file:

    test:
      override:
        - nosetests --with-coverage ~/monassis-library/monassis/tests/**/*
      post:
        - pip install requests[security]
        - codeclimate-test-reporter

Let me know if the image doesn't open with sufficient resolution to read it all. I can copy and paste the trackback if necessary.

Cheers.

![code climate test reporter 2](https://cloud.githubusercontent.com/assets/10650767/19808330/aeaa2424-9d24-11e6-9463-f00b6f40b922.png)

**Comment by dblandin** [comment]
@SiyavulaMachine,

Bummer. Is your project open source? If not, would it be possible for you to create an open-source example that reproduces the same error? I'm wondering if there's something special about your Circle CI configuration that is causing these SSL errors. I might also contact [Circle CI support](https://circleci.com/contact/). They'll have greater ability to introspect the machine configuration and might have some experience with this issue.

Thanks!

**Comment by dblandin** [comment]
Hey @SiyavulaMachine,

Is this still an issue for you?

**Comment by RichardCochrane** [comment]
Hi Devon,

It hasn’t happened for a while now so I guess it isn’t.

Thanks for checking up.

Richard

**Comment by dblandin** [comment]
Glad to hear that! :ok_hand:
