### ISSUE TITLE
Allow running without git

### ISSUE THREAD

**Issue by andrewmichaelsmith** [codeclimate/python-test-reporter#46]
We run our tests inside a docker container, the image of which we want to keep as light as possible.

From what I can see the current python plugin assumes `git` is available, in our case it is not.

Would it be possible to skip the calls to git by providing a GIT_SHA environment varibale?

**Comment by dblandin** [comment]
Hi @andrewmichaelsmith,

I'd recommend checking out our new test reporter: https://github.com/codeclimate/test-reporter

It provides better support for providing commit information via environment variables.

**Comment by dblandin** [comment]
Going to go ahead and close this issue. We have much better support for git-related environment variables in our new test reporter. I definitely recommend checking it out!
