### ISSUE TITLE
Will not run with Coverage 4.4.1

### ISSUE THREAD

**Issue by blndev** [codeclimate/python-test-reporter#49]
I expect that Version 4.4 of Coverage.py is supported.

I receive this Error Message:
> 0.36s$ codeclimate-test-reporter
>             This reporter is compatible with Coverage.py versions >=4.0,<4.4.
>             Your Coverage.py report version is 4.4.1.
>             Consider locking your version of Coverage.py to >4,0,<4.4 until the
>             following Coverage.py issue is addressed:
>             https://bitbucket.org/ned/coveragepy/issues/578/incomplete-file-path-in-xml-report

**Comment by blndev** [comment]
Currently solved with a workaround. 
I install via "pip install coverage==4.3" in travis.yml before installing other dependencies.

Then other tools like pytest-cov will not install a newer version (e.g. 4.4)

**Comment by dblandin** [comment]
@blndev That sounds like a good workaround for now. I remember that there was a compatibility issue introduced in 4.4: https://github.com/codeclimate/python-test-reporter/issues/40

Additionally, I'd recommend checking out our new test reporter: https://github.com/codeclimate/test-reporter

Its architecture is decoupled from the coverage tool used to generate the report so you can manage your coverage.py usage separately.

**Comment by dblandin** [comment]
Going to go ahead and close this issue. I think the error message from the reporter is pretty clear 👍
